#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group dancewolf.
groups:
  - ubuntu: [root,sys]
  - dancewolf
  - docker  

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: dancewolf
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZI1v5I9bClvs9yLFn+KdevjXVswd7NQ+D6kDkazeBG8h1PsFxSiQ7gvrgmvlpAVeGAm9UjmSZ2pgIf3sWyLycj08zp5FvzCPaoxFZ8A0GC7Ji4xPeqId9u7PLntMlAbaSC4YE4tjoF0Ia4Q3mstMAqp+Qaaz3/+X0SZH7VRATT8mBZ7dOMtuw1fdSXy4Kd0o/nKpy8X2xDzwMuv8OnfBdOVR2ncFfeS9UsQAJtEEa+ftQfMTkfXKtcjSPCSaTimyc+oKPQRdmrnkbZ19yfzdXWoEY18OpR/P2VwFRWzjXanfEXFZCIH3/zQTyxiUSfA2ozNzI+YWWf6vg9V3iuPa9 grahamallen@Grahams-MacBook-Pro.local 


